### ISSUE TITLE
add a date widget

### ISSUE THREAD

**Issue by akeshavan** [ReproNim/schema-ui#24]
1. add a new folder here: https://github.com/ReproNim/schema-ui/tree/master/src/components/Inputs (called "date")

2. https://github.com/ReproNim/schema-ui/blob/master/src/components/InputSelector/InputSelector.vue#L43

maybe try this UI:
https://www.npmjs.com/package/vuejs-datepicker

**Comment by akeshavan** [comment]
@sanuann : I think the date widget you've added is great for recent dates, but I wonder if, for date of birth, a set of 3 dropdowns would be more efficient (year, month, day) -- because on the calendar view it takes many clicks for me to get to my birth year :) 

perhaps it could be called "DateDropdown" ?

**Comment by sanuann** [comment]
@akeshavan can you please take a look here: https://github.com/ReproNim/schema-ui/blob/master/src/components/Inputs/DateInput/DateInput.vue#L3 
the `:not-before="new Date()"` should disable future date. not able to figure out why it doesn't work.

**Comment by sanuann** [comment]
my mistake. was referring to another vue component! figured out and fixed it.
