### ISSUE TITLE
Export data (time stamped)

### ISSUE THREAD

**Issue by sanuann** [ReproNim/schema-ui#31]

**Comment by akeshavan** [comment]
I'm going to close this, because https://github.com/ChildMindInstitute/mindlogger-web handles audio file data export to a server (e.g see https://github.com/ChildMindInstitute/mindlogger-web/pull/25 and also https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/104)

**Comment by akeshavan** [comment]
If we want to add this as a fully client-side feature, we can reopen.
