### ISSUE TITLE
Things required to make it production-ready

### ISSUE THREAD

**Issue by sanuann** [ReproNim/schema-ui#41]

**Comment by sanuann** [comment]
- [ ] For a potential participant in the voice study, we need a landing page that tells them what this study is about.
- [ ] We need a consent form like Satra’s prototype
- [ ] We need some sort of image to represent it nicely on the Mindlogger-web website.

**Comment by satra** [comment]
we may or may not need a consent form (that's going to be an optional component), also lets make the birth certificate upload invisible for now.

**Comment by sanuann** [comment]
duplicate of other issues. so closing this for now.
